### PR TITLE
Add ability to copy url sig keys and fix view url sig keys

### PR DESCRIPTION
**Pull request by DylanVolz**
fixes https://issues.apache.org/jira/browse/TC-336
fixes https://issues.apache.org/jira/browse/TC-148

### CODE REVIEW

**Comment by dneuman64** [comment]
A few things with this PR:  
1) If I choose to copy URL Sig keys the "From which DS" drop down is never populated
2) It looks like the all of the buttons that used to be conditional (Manage SSL Keys, Manage Steering Assignments, Create URL Sig Keys, etc) are now always show.
3) Adding two more buttons creates some collisions with the close button depending upon the options you have chose.
4) I think it would be cleaner to have a "manage URL Sig Keys" button rather than a generate and a copy

This PR has been out there for a while and I have been promising to review and haven't so I think I am going to see if I can clean some of this up quickly and PR it back to you.

**Comment by dneuman64** [comment]
ok, so I think at least some of these issues are with my environment. 
After talking with Dylan we decided it's best to remove the UI components from the PR, leave in the API components and then he will submit a new PR which adds the functionality to the new Traffic Portal UI.

**Comment by DylanVolz** [comment]
I have reverted the UI changes, and this PR is ready to be evaluated as an API change only.

**Comment by dneuman64** [comment]
One last thing, can you update the documentation [here](https://github.com/apache/incubator-trafficcontrol/tree/master/docs/source/development/traffic_ops_api)?  It doesn't look there is any `urlkey` docs.

**Pull request closed without merging**
