### PR TITLE
update portal ds fields

### PR DESCRIPTION
**Pull request by ashish-timilsina**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1602/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1629/
Test PASSed.

**Comment by mitchell852** [comment]
you probably want to just open a new PR, right?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1648/
Test PASSed.

**Pull request merged**
