### PR TITLE
[TC-437] - adds the ability to generate an ISO to the api / traffic portal v2

### PR DESCRIPTION
**Pull request by mitchell852**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/4/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/6/

**Comment by dangogh** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/7/

**Comment by dangogh** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/8/

**Comment by dangogh** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/9/

**Comment by dangogh** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/10/

**Comment by mitchell852** [comment]
The ISO created was verified in this manner:

sudo mkdir /mnt/iso
sudo mount -t iso9660 -o loop this-is-the-iso-created.iso /mnt/iso/
df -h
cd /mnt/iso
sudo cat ./ks_scripts/password.cfg
sudo cat ./ks_scripts/network.cfg
sudo cat ./ks_scripts/disk.cfg
sudo cat ./ks_scripts/state.out

**Pull request closed without merging**
