### PR TITLE
Add Multiple custom access logs and Header field for ATS

### PR DESCRIPTION
**Pull request by weifensh**
As discussed in the dev maillist: 
Currently TO supports only one custom access log file by configuring the "LogFormat" and "LogObject" parameters for "logs_xml.config". We have a requirement to support multiple custom access log files. As ATS does support this, we are planning to extend "LogFormat"&"LogObject" on TO, and add extra 9 groups (9 should be enough) of parameters like: "LogFormat1"&"LogObject1", "LogFormat2"&"LogObject2" ... "LogFormat9"&"LogObject9". Only when "LogFormatN"&"LogObjectN" are configured, they will appear in "logs_xml.config"; otherwise the file does not change, so the current behavior does not change either.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/26/

**Comment by dg4prez** [comment]
The configfiles.pm in UI is deprecated.  These changes need to be made against the traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm file.  If you can do that I will test and merge them.

**Comment by weifensh** [comment]
@dg4prez changes made on ApacheTrafficServer.pm as well

**Comment by smalenfant** [comment]
@weifensh I installed this today in my lab. Can you give a little more explanation on how this should work? I removed LogFormat and created a LogFormat1 and LogFormat2. This resulted with my file having the following :

```
<LogFormat>
  <Name = ""/>
  <Format = ""/>
</LogFormat>
<LogObject>
  <Format = ""/>
  <Filename = ""/>
  <RollingEnabled = />
  <RollingIntervalSec = />
  <RollingOffsetHr = />
  <RollingSizeMb = />
</LogObject>
```

**Comment by smalenfant** [comment]
@weifensh Here's an example of the parameters I imported. https://gist.github.com/smalenfant/6eb39724b9ddea55def4e99c5803733b

**Comment by smalenfant** [comment]
@weifensh Apparently I needed the old ConfigFiles.pm as well... 

@dg4prez Are both ConfigFiles.pm and ApacheTrafficServer.pm even with new ORT and API end point?

**Comment by dg4prez** [comment]
ConfigFiles is deprecated.  The api is kept up to date.

**Comment by weifensh** [comment]
@smalenfant the original "LogFormat" and "LogObject" could still be kept and still works. And new "LogFormatN" and "LogObjectN" could be added, each "LogObjectN.Format" may be assigned with the value of "LogFormatN.Name" so that they are linked.

**Comment by smalenfant** [comment]
@weifensh Could you rebase so I can merge this change? Thanks. It's been tested and working great here.

**Comment by weifensh** [comment]
@smalenfant Rebased, could you check if it is mergeable now?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/682/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/641/

**Comment by smalenfant** [comment]
@weifensh Still got problem merging (through github). We might need some assistance on how to fix this.

**Comment by smalenfant** [comment]
@weifensh I followed instructions here for `rebase -i`. Can you try the same?

https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request

basically, those following commands

```
git merge-base <branch> master
git rebase -i <commit_hash>
squash your commits
force-push
```

Hopefully that can do it. It will bring your commit as a single one on the top to the tree.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/658/

**Comment by weifensh** [comment]
Thanks @smalenfant Haven't managed to rebase it successfully, so just opened a new PR: 
https://github.com/apache/incubator-trafficcontrol/pull/1599

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/699/
Test FAILed.

**Pull request closed without merging**
