### PR TITLE
Change Monitor to default poll timeout to 10s and warn if parameter is missing

### PR DESCRIPTION
**Pull request by rob05c**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/773/
Test PASSed.

**Comment by elsloo** [comment]
10 seconds is a long time for something like this. If a cache can't respond in a few seconds we should take if out of service. For reference, the prior version's timeout for the `health.connection.timeout` parameter was 2 seconds.

**Comment by rob05c** [comment]
@elsloo I agree it's pretty long, but this is a default, in practice nobody should ever leave this Parameter unset. But if they do, I'd think we should err on the side of caution, in case the person has a slow or less-than-ideal network, in which case a too-fast timeout would make them unable to ever poll. It does give a Warning (which I was tempted to make an Error).

**Comment by elsloo** [comment]
In practice people very likely could overlook the parameter, especially those that are new to running a Traffic Control CDN. A long timeout, such as 10 seconds, could end up masking legitimate response time problems. Part of Traffic Monitor's job is to remove slow or unresponsive caches from service in order to preserve the experience on behalf of the clients. If the default timeout is too high, legitimate issues could be masked and a cache that serves all requests under the default, say in 9.8 seconds, would remain in service with a diminished user experience.

Conversely, if the short default timeout does actually cause problems and healthy caches are being removed from service, the operator should see the behavior and look to rectify the problem. Especially true if they are aware they are operating on a slow network. They will need to find and adjust this setting, but I would argue that this is going to be less likely. More likely is the scenario of an unhealthy cache staying in service due to a high default setting for this.

2 seconds (or something near it) seems like a decent threshold for such timeouts because if the path to the cache is good, there's no reason why the connection cannot be established under 2 seconds, or for the entirety of the poll to complete.

**Comment by rob05c** [comment]
Changed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/775/
Test PASSed.

**Pull request merged**
