### PR TITLE
Change TM default conf port to 80

### LINKED ISSUE #1973: Default Traffic Monitor Port is 8080 but docs and TR reference 80
Go Traffic Monitor listens on port 8080 by default. 

The installation docs describe the GUI as being on port 80. 
The TR bootstrap hosts line also references TM on port 80. 

These should all match for a simpler install.

### PR DESCRIPTION
**Pull request by rob05c**
Changes TM default conf port to match docs and old TM.

Fixes #1973

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1250/
Test PASSed.

**Comment by dneuman64** [comment]
Do you feel like this would also be a good time to move that httpListener config to traffic_monitor.cfg?  It doesn't make a lot of sense to have it in the traffic_ops.cfg file, in fact its quite confusing to new users because they think it's the port that TO is listening on.

**Comment by rob05c** [comment]
I'd support moving everything in `traffic_ops.cfg` and getting rid of it. 

I think the original idea was that we'd have a generic Traffic Ops config file in the repo, that all apps that connect to TO could use, and put the same file in their repos. That never really worked out, and it doesn't make sense to check in a valid file, e.g. with users and passwords.

I vote remove it, put all configs in `traffic_monitor.cfg`. There aren't very many.

**Comment by rob05c** [comment]
I can add that to this PR, if no one objects

**Pull request merged**
