### PR TITLE
[WIP] Travis ci

### PR DESCRIPTION
**Pull request by limited**
We probably don't want to merge this until we discuss options further, but just want to share the code for reference.

### CODE REVIEW

**Comment by knutsel** [comment]
@limited - I think this may only need the .travis file still? Can you take a look?

**Comment by limited** [comment]
Probably need to revisit based on latest dockerbuild stuff. 

However, I was holding up on this because I thought someone, maybe @dneuman64 was looking at other CI options? 

I'll send a question out to dev@ and see if we can finally get something public setup.

**Comment by dneuman64** [comment]
It's not something that I was looking at, but I agree its something that needs to be done and I can help out.

**Comment by dneuman64** [comment]
I think this can be closed now that we have jenkins on apache infra?

**Pull request closed without merging**
