### PR TITLE
[TC-550] 	User's DSes - when based on tenancy skip DS/User table - Back-port to 2.1.x

### PR DESCRIPTION
**Pull request by nir-sopher**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/214/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/173/

**Comment by dangogh** [comment]
@nir-sopher please change the title -- needs to have description of what changed.

**Comment by hbeatty** [comment]
GH issue #884

**Pull request merged**
