### PR TITLE
Fix steering race condition in TR

### PR DESCRIPTION
**Pull request by rawlinp**
Don't proactively remove Steering data for delivery services not yet in
the CRConfig.json. This data is not "invalid" and can safely be kept.
This fixes the race condition where a user updates steering assignments
for delivery services that don't exist in CRConfig yet that causes the
steering delivery service to be unusable.

### CODE REVIEW

**Comment by rawlinp** [comment]
Fixes #1145

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/975/
Test PASSed.

**Comment by rawlinp** [comment]
This mostly works except for a slight hitch in the case of STEERING DSes being consistent-hashed to a target that's not yet in CRConfig. I will fix that shortly.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/981/
Test FAILed.

**Comment by rawlinp** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/982/
Test PASSed.

**Pull request merged**
