### PR TITLE
Replacing deprecated traffic_line with traffic_ctl

### LINKED ISSUE #1128: ORT: traffic_line deprecated in ATS 7.x
ORT should use `traffic_ctl config reload` instead of `traffic_line -x` in ATS version 5.3 and higher.

`traffic_line` is deprecated in 7.x

### PR DESCRIPTION
**Pull request by smalenfant**
Closes #1128

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-whatchanged/64/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/195/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/156/

**Comment by alficles** [comment]
This looks good to me. This is one of several important steps toward bringing TC up to where it can support ATS 7.x and forward.

**Comment by smalenfant** [comment]
Closing as there was just another pull request to do the same.

**Pull request closed without merging**
