### PR TITLE
Add TO Client refreshing cookie on auth fail

### LINKED ISSUE #1523: 401 Causes TM to lose visibility into TO API
It appears that if Traffic Monitor is unable to authenticate with Traffic Ops at some point after doing so successfully in the past it will not recover. We should test more to confirm the behavior, then fix the bug as appropriate.

### PR DESCRIPTION
**Pull request by rob05c**
Fixes #1523

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/643/
Test PASSed.

**Comment by asfgit** [comment]
FAILURE
 No test results found.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/600/

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/650/
Test PASSed.

**Comment by asfgit** [comment]
FAILURE
 No test results found.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/607/

**Comment by asfgit** [comment]
FAILURE
 No test results found.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/608/

**Comment by rob05c** [comment]
Fixed merge conflicts

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/655/
Test PASSed.

**Comment by asfgit** [comment]
FAILURE
 No test results found.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/613/

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/615/

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/657/
Test PASSed.

**Pull request merged**
