### PR TITLE
[issue 1814] Add fields to the reponse of POST/PUT steering target APIs

### LINKED ISSUE #1814: response fields are not complete in POST/PUT steering target APIs
In the response of POST/PUT steering target APIs, the following fields are missing: deliveryService, target and type.

Similar to other APIs such as deliveryservice and server, the name fields need be responded beside the id fields.

### PR DESCRIPTION
**Pull request by jifyang**
This fixes #1814

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/943/
Test FAILed.

**Comment by jifyang** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/945/
Test FAILed.

**Comment by dangogh** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/954/
Test FAILed.

**Comment by mitchell852** [comment]
@jifyang - can you update the documentation too?

https://github.com/apache/incubator-trafficcontrol/blob/master/docs/source/development/traffic_ops_api/v12/steering_target.rst

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/969/
Test FAILed.

**Comment by jifyang** [comment]
@mitchell852 - the document is updated. thanks

**Pull request merged**
