### PR TITLE
WIP -- cfg_test.pl rewritten in go

### PR DESCRIPTION
**Pull request by dangogh**
not ready for primetime,  but a concept..  concurrently make api calls to 2 different TO instances.  Can be used to compare master to previous release or go TO to perl TO,  e.g.

Currently checks for exact match of json body -- does not attempt any reordering of keys,  etc,  but written to files so comparison can be done e.g. via `jq -S ...`

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/640/
Test PASSed.

**Comment by asfgit** [comment]
FAILURE
 No test results found.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/597/

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/641/
Test PASSed.

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/598/

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/646/
Test PASSed.

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/603/

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/659/
Test PASSed.

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/618/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/730/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/735/
Test FAILed.

**Comment by dangogh** [comment]
opening separate -- scope changed

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/779/
Test PASSed.

**Pull request closed without merging**
