### PR TITLE
fix alert test

### PR DESCRIPTION
**Pull request by dangogh**
signature changed on called func

### CODE REVIEW

**Comment by dangogh** [comment]
@DylanVolz please review

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/916/
Test PASSed.

**Comment by DylanVolz** [comment]
Looks good, this is exactly what this test needed after my refactor when I missed it.

**Comment by mitchell852** [comment]
merging based on @DylanVolz recommendation

**Pull request merged**
