### PR TITLE
[BACKPORT] [TC-441] - corrects reset password link to match format of TP

### PR DESCRIPTION
**Pull request by mitchell852**
(cherry picked from commit 404b4a0362a38c2656b53cbe056b7675b902c162)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/71/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/111/

**Comment by hbeatty** [comment]
@mitchell852 merged - please close

**Comment by mitchell852** [comment]
manually closing

**Pull request closed without merging**
