### PR TITLE
[#880] sets correct defaults for MSO parameters

### PR DESCRIPTION
**Pull request by dg4prez**
this commit corrects the defaults for MSO parameters and ignores invalid server retry response parameters.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-whatchanged/68/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/160/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/199/

**Comment by dneuman64** [comment]
This closes #880

**Pull request merged**
