### PR TITLE
[BACKPORT][TC-540] fix postinstall ldap.conf keys; prompt for base_url

### PR DESCRIPTION
**Pull request by dangogh**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/90/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/130/

**Comment by dangogh** [comment]
@hbeatty hold off on this one -- found a glitch....

**Comment by dangogh** [comment]
@hbeatty ready for merge now..

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/141/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/102/

**Comment by hbeatty** [comment]
@dangogh merged - please close

**Comment by hbeatty** [comment]
Haha! I can close it now.

**Comment by dangogh** [comment]
@hbeatty ahh..  the simple joys in life....

**Pull request closed without merging**
