### PR TITLE
[Issue-1550] WIP -- TO golang -- adds orderby= parameter handling to endpoints

### PR DESCRIPTION
**Pull request by dangogh**
First stab at it -- may need a bit more work.

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/606/

**Comment by asfgit** [comment]
FAILURE
 No test results found.
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/649/
Test FAILed.

**Comment by dangogh** [comment]
Fixes #1550

**Pull request merged**
