### PR TITLE
Create code of conduct

### PR DESCRIPTION
**Pull request by ashish-timilsina**
Not sure users can report issues. Don't think receiving comments in the dev mailing list is the best way but as some users may not feel comfortable talking about these issues in public. Maybe we create some form in the traffic control site and users can anonymously report issues.

### CODE REVIEW

**Comment by rob05c** [comment]
We should discuss this on the mailing list. There's been an awful lot of controversy in numerous Open Source projects in the last year surrounding Codes of Conduct.

I think Apache rules require us to discuss and achieve consensus on the mailing list for something this big.

**Comment by alficles** [comment]
I believe this project is already covered by the existing code of conduct here: https://www.apache.org/foundation/policies/conduct.html

Rather than create a potentially conflicting one, perhaps it would be better to simply refer by link to the one already in place?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/480/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/526/
Test PASSed.

**Comment by ashish-timilsina** [comment]
Thanks @rob05c and @alficles for your feedback. Yeah, this topic came up at the Traffic Control Summit in Atlanta so I wanted to get us started. Since the code of conduct is already covered by the apache foundation, I agree there's no need to create a new one. I will bring it up in the mailing list

**Pull request closed without merging**
