### PR TITLE
TC-7 simplify psql conversion using docker-compose

### PR DESCRIPTION
**Pull request by dangogh**

### CODE REVIEW

**Comment by dangogh** [comment]
https://issues.apache.org/jira/browse/TC-6

**Comment by mitchell852** [comment]
i already merged this into the psql branch...not quite sure why it's still open...maybe asfgit is taking a nap

**Comment by dangogh** [comment]
because it's not on master..   it'll only close it once it's merged on master

**Comment by dangogh** [comment]
already merged on psql

**Pull request closed without merging**
