### PR TITLE
[BACKPORT] [TC-519] - adds back missing tenants menu item

### PR DESCRIPTION
**Pull request by mitchell852**
(cherry picked from commit a049589041ece51d6069cae09e2fdf23440d4a91)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-traffic_ops-test-PR/32/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/70/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/4/

**Comment by hbeatty** [comment]
@mitchell852 merged - please close

**Comment by mitchell852** [comment]
manually closing

**Pull request closed without merging**
