### PR TITLE
[Issue 1838] add `/api/1.3/about` endpoint and `-version` option on cmd line

### LINKED ISSUE #1838: Expose TrafficOps Version Info via API
As a TO developer, I would like be able to issue an API query to get the installed version of TrafficOps so that I can know what has changed since the current production release.  Currently this information is only available via TO/TP about boxes in the GUI.  It should require at least read-only level permissions so it's not generally available to the world.

### PR DESCRIPTION
**Pull request by dangogh**
Version is set during `go build` during rpm build.

This fixes #1838

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1221/
Test PASSed.

**Comment by dewrich** [comment]
Should there be an API test as well?

**Comment by dewrich** [comment]
Fixes https://github.com/apache/incubator-trafficcontrol/issues/1838

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1228/
Test PASSed.

**Comment by dewrich** [comment]
All tests function and looks good

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1232/
Test PASSed.

**Pull request merged**
