### PR TITLE
[Issue-1189] - delivery service tenancy is forced on creation and update if use_tenancy is on

### PR DESCRIPTION
**Pull request by nir-sopher**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/280/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/238/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/239/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/281/

**Comment by nir-sopher** [comment]
I prefer to make the extra test.
It allows gradual transition to the tenancy world - if for a point in time
only part of the DSes were added with tenancy, I want the user to be able
to change a non tenant DS ASAP without dealing with tenancy.

**Comment by mitchell852** [comment]
I still think if use_tenancy is turned on then there are certain expectations of a delivery service. And one expectation is that ALL delivery services are assigned to a tenant.

If you have ds's that are not or shouldn't be assigned to a tenant, then maybe you aren't ready to turn on tenancy. It's seems like tenancy is all or nothing...

(remember, you can always use the old TO UI if you really don't want to assign a tenant to a ds...)

**Comment by mitchell852** [comment]
Here's the problem. It's a big risk to allow a DS to not have a tenant when use_tenancy is turned on.

Because ds's without a tenant are visible to EVERYBODY, right? That is probably not what you intended when you left tenant=null...

**Comment by nir-sopher** [comment]
Jeremy.
I do not see the risk here.
If you already changed all DSes to have tenancy, you are safe (as I do not allow adding a "no-tenant" DS, and I do not allow removing the tenancy). 
If you haven't changed tenancy of all DSes, you are not safe by your definition and forcing any change of the DS to also assign tenancy doesn't make it any safer.

I understand your point - you cannot make the system wide open if tenancy is not fully set. But why to lose this flexibility?

**Comment by mitchell852** [comment]
I see your point @Nir. If you can't create a ds without a tenant and you can't set tenant to null (where it was defined before), I'm good with that.

**Pull request merged**
