### PR TITLE
Adding TXT Records support

### PR DESCRIPTION
**Pull request by smalenfant**
This adds TXT Record support to Traffic Router. To enable, you must also add a `TXT` Type in Traffic Ops and add your static record under your delivery service.

Added the feature so it could be used with Let's Encrypt (TBD).

### CODE REVIEW

**Comment by smalenfant** [comment]
Didn't put the DB migration to include TXT in the standard types. I'd like some recommendations regarding that area.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/839/
Test PASSed.

**Comment by smalenfant** [comment]
@elsloo Just added the seeds for that type of record as well. 
@rob05c I believe this should be good to go, but double check with Jeff. This is really for Let's Encrypt support. They are coming this month with wildcard certificates which requires DNS challenge.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/931/
Test PASSed.

**Comment by rivasj** [comment]
@smalenfant this PR has compilation failures, and when corrected, unit test failures. Please revisit

**Pull request merged**
