### PR TITLE
[TC-72] Dockerfile build local

### PR DESCRIPTION
**Pull request by dangogh**
Reworked docker-compose.yml and Dockerfiles for component builds to use local directory rather than cloning from github.

### CODE REVIEW

**Comment by dangogh** [comment]
@rob05c -- `traffic_monitor` and `traffic_monitor_golang` both produce the same name rpm.  Does the former need to be removed from the `docker-compose.yml`?

**Comment by dangogh** [comment]
@limited -- is this what you had in mind?   Perhaps should be considered for merge into 2.0? (for Apache compliance)

**Comment by alficles** [comment]
@dangogh @rob05c Yeah, `docker-compose up` should build all the things. As it stands, you'll get either a build failure or, worse, an unlabeled and arbitrary traffic_monitor binary in the output. I would strongly consider deciding which one is "mainstream" and either commenting out the build steps for the other, or reconfiguring the build to put the other's binaries in a different subfolder (which might be tricky).

**Comment by alficles** [comment]
This is a marked improvement, but it introduces a new issue: `make clean`. Since the build is happening directly in the local directories, all the temporary files will be left around. There's two ways around this, either copy the entire build folder into a new directory inside the container and just copy the final binaries out, or introduce a cleaning functionality that will remove the intermediate files.

I like the second option better, but the first is significantly easier, I think.

**Comment by rob05c** [comment]
@dangogh @alficles Yes, traffic_monitor and traffic_monitor_golang should
never both be built. One is replacing the other. The plan is to rename the
`traffic_monitor_golang` directory to `traffic_monitor` and remove the old
`traffic_monitor` once it's stable. Until we change the name and officially
"replace" the old one, Docker Compose shouldn't build
`traffic_monitor_golang`.

+1 on commenting it. Leaving in there and commented will make it easier for
those of us testing the new version.

**Comment by dangogh** [comment]
that's what I needed to know..   thanks..

**Comment by dangogh** [comment]
@alficles -- copying the repo wouldn't be easier:  chicken vs egg.  docker-compose operates from that directory,  so would need to switch to the copy mid-stream.   Cleaning up would be the better option, IMO.  Main thing is rpmbuild dir.   Some remnants left in TM and TR dirs.  But any clean operation would need to avoid messing with other files *not* created by the build process...

Perhaps deleting the rpmbuild dir would be sufficient for now..

**Comment by alficles** [comment]
Here's what I do on the ats-rpmbuild side:

```
#!/usr/bin/env bash

if [ ! -d /src ]; then
        echo "Source directory does not exist."
        exit 1
fi

cp -r /src /build

cd /build
autoreconf -vfi
./configure --prefix=/opt/trafficserver --enable-experimental-plugins --with-max-api-stats=4096
make DESTDIR=/artifacts -j install
```

So the idea is to mount the "live" folder, then copy it to a build folder, build, and copy back the relevant artefacts.

**Comment by dangogh** [comment]
@alficles -- latest should address those clean concerns..

@limited -- please consider pulling in to 2.0

**Comment by limited** [comment]
noted, will see how the merge looks. probably a go

**Comment by alficles** [comment]
Ok. I've tested this. It correctly produces binaries in the `dist` directory, without polluting your environment. For anyone else testing, make sure your docker is on the absolute latest. There's a bug in the penultimate build that is exercised by the `cp -a` in the new script.

I'm +1 on this merge, with a few comments:

- The `BUILD.md` file doesn't list the new tarball build option. This is a particularly useful option.
- The `BUILD.md` identifies the wrong target folder.
- The build command is really quite long. This is just an opinion, but we may want to add a tiny script that encodes the commands prescribed by `BUILD.md`.

**Comment by dangogh** [comment]
adding those 2 things to BUILD.md shortly..    For last point,  I think deal with it separately.   Created issue https://issues.apache.org/jira/browse/TC-180 for that.

**Comment by alficles** [comment]
+1. This is good to merge.

**Pull request closed without merging**
