### PR TITLE
[WIP] [Issue-1493] Specify bypass URL port in CrConfig only if explicitly set

### PR DESCRIPTION
**Pull request by oren-shemesh**
This fix makes Traffic Ops specify the 'port' field in the 'bypass' section of
CrConfig only if explicitly set in the DS 'Bypass FQDN' field (By using the format 'fqdn:port').
(Relevant for HTTP DSes only)

Before the fix, if a port was not explicitly set in the DS 'Bypass FQDN' field,
Ops specified a value of 80 to the 'port' field in CrConfig, making HTTPS requests that
go to bypass being redirected to https://<bypass-fqdn>:80/... , which is
certainly not right.

Resolves: #1493 TR redirects to Bypass FQDN with port 80 for HTTPS DSes

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/609/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/565/

**Comment by rawlinp** [comment]
This change looks good to me. I'm not sure what's going on with the build check, but it doesn't look at all related to your change.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/687/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/646/

**Comment by oren-shemesh** [comment]
Many unrelated commits were somehow added to this PR, closing it in order to make a new one

**Pull request closed without merging**
