### PR TITLE
move all defer rows.Close() calls directly beneath query call

### PR DESCRIPTION
**Pull request by DylanVolz**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/584/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/540/

**Comment by PSUdaemon** [comment]
If `err` is not `nil` is it safe to call `Close()` on `row`?

**Comment by DylanVolz** [comment]
Yes, it is safe to call close on a nil rows object. Looking at the source
code it is unnecessary because if the err returned isn't nil the rows will
be nil, but I liked having it located right by the call.

**Comment by rob05c** [comment]
@DylanVolz I know this is already merged, but I'd just like to say, I'm +1 on calling `Close()` after checking the err, -1 on calling before, because:
* even if it's safe in this particular instance, the Go idiom is to always check errors before objects, and that objects aren't guaranteed to be valid (and for pointers, to be non-nil) if `err` is non-nil
* It's not even theoretically safe here. You're right, the current source is safe, but that's an implementation detail. There's no guarantee in the spec or documentation, which means it could become unsafe in the next release.
* Even if it were guaranteed in the spec, IMO we should still check the err first, following the idiom, because it's safer as a pattern. If we call functions before checking the error in places it's technically safe, someone new to Go could easily see them, think it's generally safe, and write a bug. Better to use the safe pattern everywhere, unless there's a compelling reason not to.

**Pull request merged**
