### PR TITLE
[WIP] CDN table, DS profiles, and ATS 6.2 support

### PR DESCRIPTION
**Pull request by knutsel**
This is a work in progress, but getting really close. I'll make a wiki page describing the changes in this soon, and still have to do the documentation, but I think it's all working. Fixes a handful of JIRAs and more.

### CODE REVIEW

**Comment by knutsel** [comment]
See also https://cwiki.apache.org/confluence/display/TC/PR+%23273

**Comment by knutsel** [comment]
I don't know why it says `This branch cannot be rebased due to conflicts` - i am merged onto the latest master.

**Comment by dangogh** [comment]
Doesn't look like it...    `git merge-base master cdn-table-1` shows me this commit:
```commit 224eab5c10d8b5e0ebedf18edfb375e0f3c0cff0
Author: Jeff Elsloo <jeffrey_elsloo@cable.comcast.com>
Date:   Fri Feb 3 11:17:58 2017 -0700

    This closes #250.
```
and there's a conflict in `traffic_ops/app/lib/UI/DeliveryService.pm` after rebasing...

**Comment by knutsel** [comment]
Closing this in favor of a rebased one that I'll PR soon.  Thanks for helping with git (again) @dangogh .

**Pull request closed without merging**
