### PR TITLE
[BACKPORT] [TC-535] - 2.1.x url sig tenancy checks

### PR DESCRIPTION
**Pull request by mitchell852**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/89/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/129/

**Comment by hbeatty** [comment]
@mitchell852 merged - please close

**Comment by hbeatty** [comment]
merged. closing.

**Pull request closed without merging**
