### PR TITLE
Add Traffic Monitor CRConfig history endpoint, rejecting bad configs

### PR DESCRIPTION
**Pull request by rob05c**
This makes it possible to debug Traffic Ops sending the wrong CRConfig, an older CRConfig, or the Traffic Ops FQDN resolving to a wrong IP (for example, if a GSLB was misconfigured).

This also adds an additional safeguard, in addition to the one in the Router, to make the Monitor reject a CRConfig it receives older than the one it has, or with the wrong CDN.

This depends on #1468 and should be merged after it.

### CODE REVIEW

**Comment by rob05c** [comment]
Fixed conflicts.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/570/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/614/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/622/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/579/

**Pull request merged**
