### PR TITLE
Test for ats version when building remap - switch cachekey/url

### PR DESCRIPTION
**Pull request by ezelkow1**
Currently when building the remap line we always use the cacheurl plugin and the generic cacheurl_qstring.config file if qstring_ignore=1.  This needs to be changed for ATS >=6 to use cachekey since starting with ATS 7 we no longer have the cacheurl plugin.

Tested this on my dev environment and could see the remap output changing based on my hardcoded default value when it was not assigned in the server info.  This will need more testing with a prod-type environment

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by mitchell852** [comment]
this looks fine to me but you might want to have @dg4prez take a look at it as well.

**Comment by dg4prez** [comment]
The config generation side looks good.  I've spoken with Evan who will be taking point on the staging and lab testing to ensure that these settings do not cause problems with ATS in production.

**Pull request merged**
