### PR TITLE
[BACKPORT] [TC-441] - refactored how tokin login works to ensure tokin login is complete be…

### PR DESCRIPTION
**Pull request by mitchell852**
…fore attempting to resolve other dependencies that need the authentication cookie

(cherry picked from commit 98092836c2ae5ac3382245e1b3645eefbda1c7b6)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/128/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/88/

**Comment by hbeatty** [comment]
@mitchell852 merged - please close

**Comment by mitchell852** [comment]
manually closing

**Pull request closed without merging**
