### PR TITLE
TO go: `go get` prior to running unit tests for the golang.org/x dependencies

### PR DESCRIPTION
**Pull request by dangogh**
unit tests in jenkins started failing when `golang.org/x` dependencies were removed from the vendor dir.   This gets those dependencies in the docker container prior to running the tests.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1386/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1405/
Test FAILed.

**Comment by dangogh** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1407/
Test PASSed.

**Pull request merged**
