### PR TITLE
Added traffic portal using.rst to admin docs

### PR DESCRIPTION
**Pull request by trevorhays**
There are a couple of delivery service fields that still need descriptions but it's close.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by mitchell852** [comment]
@trevorhays - i'm seeing a bunch of warning when building the docs. i.e.

	/code/src/github.com/apache/incubator-trafficcontrol/docs/source/admin/traffic_portal/using.rst:471: WARNING: duplicate label rl-header-rewrite, other instance in /code/src/github.com/apache/incubator-trafficcontrol/docs/source/admin/traffic_ops/using.rst
	/code/src/github.com/apache/incubator-trafficcontrol/docs/source/admin/traffic_portal/using.rst:986: WARNING: duplicate label rl-queue-updates, other instance in /code/src/github.com/apache/incubator-trafficcontrol/docs/source/admin/traffic_ops/using.rst

**Comment by trevorhays** [comment]
@mitchell852 I made the changes we talked about.  I was able to get rid of all of the warnings except WARNING: unknown config value 'latex_paper_size' in override, ignoring

**Comment by dangogh** [comment]
I don't know why we'd care about paper size,  but looks like Sphinx changed the method to use it: https://github.com/sphinx-doc/sphinx/issues/2995

I'd say remove it from the Makefile

**Comment by knutsel** [comment]
@trevorhays  - Can you please double check the docs on http://traffic-control-cdn.readthedocs.io/en/latest/ after this gets merged, and let me know if they automatically update? Should be there 10 mins after merge. Don't know that I've seen doc updates yet, and wanted to keep an eye on the first one.going through.

**Comment by dangogh** [comment]
@trevorhays this really needs to be rebased and maybe squashed at least partially..   Let me know if I can help

**Comment by trevorhays** [comment]
@knutsel The docs were updated.

**Pull request merged**
