### PR TITLE
Add a Coordinates API

### PR DESCRIPTION
**Pull request by rawlinp**
Adding a Location API is the first step to refactoring lat/lon out of
the Cache Group API into its own entity - Location. With the Location
API in place, the cachegroup table can be updated to reference a
Location, and other future entities (such as Origins) can make use of
Locations as well.

This is part of the larger "geolocation-based client steering" effort.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1372/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1400/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1419/
Test PASSed.

**Comment by dewrich** [comment]
@rawlinp awesome work on crossing all the T's and dotting the I's.  We'll review this one soon!

**Comment by dewrich** [comment]
My only suggestion is `location` is overloaded in the CDN, I would have probably called it `coordinate`.  Of course a bit late to make that suggestion now 😁

**Comment by dewrich** [comment]
@rawlinp Also don't forget to update the CHANGELOG.MD 😁

**Comment by rawlinp** [comment]
@dewrich aye, this would indeed require that. Done

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1447/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1452/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1456/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1461/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1512/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1514/
Test FAILed.

**Pull request merged**
