### PR TITLE
[BACKPORT] [TC-374] eliminate TO orphan processes

### PR DESCRIPTION
**Pull request by dangogh**
(cherry picked from commit 52e50b98523902dab422117ca958655457f3de5f)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/57/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-traffic_ops-test-PR/59/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/97/

**Comment by hbeatty** [comment]
@dangogh merged - please close

**Pull request closed without merging**
