### PR TITLE
[BACKPORT] [TC-521] TPv2 - accounts for missing dependency that centos 7.3 doesn't provide

### PR DESCRIPTION
**Pull request by mitchell852**
… when centos 7.4 is available this dependency will be provided with the distro.

(cherry picked from commit 15901255c1847800bbd871e33c757017ec23f74f)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/39/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-traffic_ops-test-PR/41/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/79/

**Comment by smalenfant** [comment]
@mitchell852 Please close. Thanks.

**Comment by mitchell852** [comment]
manually closing this

**Pull request closed without merging**
