### PR TITLE
Update.jenkinsfile.test

### PR DESCRIPTION
**Pull request by jhg03a**
I brought the test branch up-to-date with the latest commits and fixed an error in the build processed with the change to 2018 in ratcheck.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by jhg03a** [comment]
hey look, ghprb figured it out.

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by jhg03a** [comment]
ok to test

**Comment by jhg03a** [comment]
test this please

**Comment by jhg03a** [comment]
Abandoning PR test

**Pull request closed without merging**
