### PR TITLE
[BACKPORT] [TC-491] [TC-492] 	deletes applicable staticdnsentries and jobs when a ds is deleted

### PR DESCRIPTION
**Pull request by mitchell852**
cherry pick of b7b293718c0ca8174dba5759c01301208d5c6a78

### CODE REVIEW

**Comment by asfgit** [comment]
FAILURE
 No test results found.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-traffic_ops-test-PR/63/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/101/

**Comment by hbeatty** [comment]
@mitchell852 merged - please close

**Comment by mitchell852** [comment]
manually closing

**Pull request closed without merging**
