### PR TITLE
[TC-177] changed psql to use URI for admin.pl in trafficops.

### PR DESCRIPTION
**Pull request by rscrimojr**
This fixes [TC-177](https://issues.apache.org/jira/browse/TC-177)

### CODE REVIEW

**Comment by dangogh** [comment]
can you change the title to mention admin.pl?   I want to be able to find this a year from now..

**Comment by dangogh** [comment]
`[--admuser (Postgres Admin User)] [--admpwd (Postgres Admin Password)]` -- this requires a password on the cmd line -- not a good idea either,  since it ends up in the shell history.   what we talked about was having the user deal with being a user that has db admin privileges.  Don't you think that would be better?

**Comment by rscrimojr** [comment]
So you want the user installing trafficops to create a postges unix user or some other admin user?

**Comment by rscrimojr** [comment]
The other thing to do is add the admin user and password as a new key in the dbconf.yml file?  Does this sound okay as an alternative?

**Comment by dangogh** [comment]
no -- they should be able to make their own user able to connect as a db admin or create postgres user with the same.   dbconf.yml is for goose.  don't change that.   I think this aspect of admin.pl should not have changed.

**Comment by rscrimojr** [comment]
okay.  I will try to do what you want when I have time.

**Comment by dangogh** [comment]
we ended up taking a different direction for running these commands,   so this change isn't needed.  Please close.

**Pull request closed without merging**
