### PR TITLE
Add Traffic Ops username to access log

### PR DESCRIPTION
**Pull request by rob05c**

### CODE REVIEW

**Comment by mitchell852** [comment]
Tested locally, here were my results:

127.0.0.1 - localUsername [05/Jun/2017:13:38:48 -0600] "GET /api/1.2/logs/newcount HTTP/1.1" 200 51 7370 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

^^ local database user

127.0.0.1 - ldapUsername [05/Jun/2017:13:39:07 -0600] "GET /newlogcount HTTP/1.1" 200 38 4830 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

^^ ldap user (user is not found in the database)

@dewrich or @dangogh  - any concerns?

**Comment by dewrich** [comment]
I think putting the username at the "end" of the line is better in case there are any logs scrapers concerned with that format.  Otherwise I think the localUsername vs. the ldapUsername seems correct to be logged accordingly.

**Comment by rob05c** [comment]
This PR doesn't modify the log format, which was already logging `%u` (which apparently broke sometime in the past), it only makes the logger aware of the username.

**Comment by mitchell852** [comment]
this is what the log line looks like now:

127.0.0.1 - - [05/Jun/2017:13:54:34 -0600] "GET /api/1.2/logs/newcount HTTP/1.1" 200 51 25823 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

so, yea, @dew it looks like the %u is there...it's just blank...

**Pull request closed without merging**
