### PR TITLE
[Issue 1541] fix integration tests for signing_algorithm change

### PR DESCRIPTION
**Pull request by dangogh**
integration test fixtures still referencing "signed" on delivery service rather than "signing_algorithm"

### CODE REVIEW

**Comment by dangogh** [comment]
This fixes #1541

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/637/
Test PASSed.

**Comment by asfgit** [comment]
SUCCESS 
 No test results found.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/594/

**Pull request merged**
