### PR TITLE
[TC-169] update last modified time if files equal

### PR DESCRIPTION
**Pull request by zhilhuan**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/42/

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/28/

**Comment by hbeatty** [comment]
GH issue #912

**Comment by dneuman64** [comment]
@zhilhuan merged. Does this need to be backported to 2.1.x?  If so, can you please do that?

**Comment by zhilhuan** [comment]
@dneuman64 Thanks! I think it is not critical and ok to wait for the next release.

**Pull request merged**
