### PR TITLE
implement servers CRUD endpoints in go

### LINKED ISSUE #1620: API: Server API sets xmpp_id to null
We have been moving servers using the API (Traffic Ops 2.1). When the server were created, we noted that the HTTP request consistent hashing was not working anymore. We discovered that the xmpp_id was set to null.

This field was present in the CR-Config under the server hostnames : 
`"hashId": null,`

### PR DESCRIPTION
**Pull request by DylanVolz**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/994/
Test PASSed.

**Comment by DylanVolz** [comment]
WIP - testing for parity with perl endpoints.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/997/
Test PASSed.

**Comment by dangogh** [comment]
Error checking needs to be improved..   With Perl version on PUT,  I removed the "cdn" and "cdnId" entries and got this message:
 ```
to-put servers/600 s.json
{"alerts":[{"level":"error","text":"CDN of profile does not match Server CDN"}]}
```
With this version,  I got this:
```
to-put servers/600 s.json
{"alerts":[{"text":"database access error","level":"error"}]}
```
and this from the log:
```
ERROR: db_helpers.go:118: failed to parse unique constraint from pq error: pq: insert or update on table "server" violates foreign key constraint "fk_cdn2"
ERROR: alerts.go:81: 2018-02-11T20:41:24.952109304Z: 96.118.253.249:56124 [database access error]
96.118.253.249:56124 - admin [11/Feb/2018:20:41:24 +0000] "PUT /api/1.3/servers/600 HTTP/1.1" 500 61 94 "curl/7.43.0"
```

**Comment by DylanVolz** [comment]
This is still WIP, working on getting the validation to match perl still.

**Comment by dangogh** [comment]
np -- I'll help :-)

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1168/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1169/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1173/
Test PASSed.

**Comment by dangogh** [comment]
Can you add api tests in `testing/api`?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1211/
Test PASSed.

**Pull request merged**
