### PR TITLE
Experimental support for Client Subnet in DNS Queries RFC7871

### PR DESCRIPTION
**Pull request by limited**
(cherry picked from commit 34e122e932d409c24a26101149a8a50a3a1a1a28)

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by elsloo** [comment]
@limited can you or someone else update this PR to use the Jackson JSON libraries, using the examples that were merged in by @rivasj when he removed all of the json.org dependencies? I can merge this once that update is complete.

**Comment by limited** [comment]
@elsloo Fixed up the JSON.org dependency.


Also I think at this point this can go into 2.3, so updating the milestone

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by limited** [comment]
ok to test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1126/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1129/
Test PASSed.

**Pull request merged**
