### PR TITLE
[TC-547] Fix regression issues caused by TC-187

### PR DESCRIPTION
**Pull request by zhilhuan**
Fix regression issues caused by TC-187:
1. revert: replace xml_id with ds_<ds-id> as riak key for ssl certificate
2. revert: decode base64 for ssl csr, crt, key in restful api

Add missing code for update ssl keystore when hostname changes

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/84/

**Comment by zhilhuan** [comment]
@rawlinp This PR reverted the regression issues introduced by TC-187. And also resolved your comments in PR#360. Please help to review.

**Comment by zhilhuan** [comment]
fatal: ambiguous argument 'TC-547': unknown revision or path not in the working tree.

This is a issue in build server, not my code, right?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/124/

**Comment by DylanVolz** [comment]
@zhilhuan Yes that was a build server issue that should be resolved now.

This PR looks good; it reverts the breaking changes introduced by the change from xmlId to id in the keysto store ssl keys in riak.

**Comment by rawlinp** [comment]
Looks good to me. Thanks for fixing this!

Note that we'll have to figure out if we want to regenerate the actual certs too (rather than just the hostname in the riak record), but we'll tackle that in a new PR once we've discussed what needs to be done about that.

**Comment by zhilhuan** [comment]
@rawlinp Thanks for your comments! Yes, that's need aother discussion, because the certs may be pasted by operator instead of generated by ops.

**Pull request closed without merging**
