### PR TITLE
[Issue-1651] - putting server.ipv6 into the database as an empty string could trigger uniqu…

### LINKED ISSUE #1651: Creating/updating a server with no ipv6 value can trigger unique constraint in database and return internal server error
creating/updating a server with ipv6=empty string triggers ipv6+profile unique constraint if there is another server with no ipv6 and the same profile.

### PR DESCRIPTION
**Pull request by mitchell852**
…e constraint

fixes #1651

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/772/
Test FAILed.

**Comment by dewrich** [comment]
@mitchell852 is this because the IPV6 addresses are optional?

**Comment by mitchell852** [comment]
@dewrich - yes, ipv6 on a server is an optional attribute, therefore, somebody could send thru ipv6= empty string which causes problems with the ipv6+profile unique constraint

this PR takes any  ipv6=empty string and converts them to null before sticking them in the database which doesn't cause the ipv6+profile unique constraint to kick in.

so basically, you can have multiple servers where ipv6=null and profile=A which is how it should be.

but before this PR, you could not have multiple servers where ipv6=emptyString and profile=A

**Comment by dewrich** [comment]
Sounds good

**Pull request merged**
