### PR TITLE
Change Traffic Ops to hide sensitive data for non-db users

### PR DESCRIPTION
**Pull request by rob05c**
Changes Traffic Ops to disallow LDAP users that don't exist in the
database from seeing any sensitive information (essentially anything
but graphs and general CDN-wide stats).

### CODE REVIEW

**Comment by mitchell852** [comment]
I'll try to check this out tomorrow. thanks @rob05c

**Comment by mitchell852** [comment]
@rob05c - you should probably share this change with the dev or user email list to ensure that no unforeseen problems come of this change.

**Comment by mitchell852** [comment]
I can't get TO to build/start

Couldn't load application from file "bin/../local/../script/cdn": Not a CODE reference at /src/github.com/apache/incubator-trafficcontrol/traffic_ops/app/lib/TrafficOpsRoutes.pm line 375, <$fn> line 1.

**Comment by rob05c** [comment]
@mitchell852 Fixed.

**Comment by mitchell852** [comment]
This PR should be merged first - https://github.com/apache/incubator-trafficcontrol/pull/642

Once that PR is merged, username will be added to access logs and that data can be used to determine who is logging in as ldap only and then a "local" user in the tm_user table can be created for those users....this will prevent those ldap only users from being totally cut off when this PR is merged...

**Comment by dangogh** [comment]
conflicts with master -- please resolve these...

**Comment by rob05c** [comment]
Fixed.

**Pull request closed without merging**
