### PR TITLE
[Issue-1722] - ensures initDispersion on http ds is greater than 0

### PR DESCRIPTION
**Pull request by mitchell852**
related to #1722

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/859/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/860/
Test PASSed.

**Comment by smalenfant** [comment]
@mitchell852 Somehow I must have lost some comments, but it was related to dispersion still set to zero and we still need to go in the "Advanced Settings" to set to Dispersion to 1 (Doesn't seem to be a required setting). I'll try to get a screenshot and send it your way.

**Comment by smalenfant** [comment]
Re-tested and it works as intended, I might have had the wrong version installed.

**Pull request merged**
