### PR TITLE
Add logging.config support for ATS 7.1.x

### PR DESCRIPTION
**Pull request by ezelkow1**
ATS 7.1.x changed the logging format from logs_xml.config to a new lua based logging.config. These changes generate the new file, and continue to use the same terminology from the previous logs_xml.config since most of the fields transfer over

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by smalenfant** [comment]
Do you think we could share the same logs_xml entries for this? Is there a way to detect ATS 6 vs 7?

**Comment by ezelkow1** [comment]
we could, thats how I originally tested it by just hardcoding to use the params from the logs_xml before I had a test profile setup to use logging.config. 

Problem is the rest of the code triggers off of the filename specified in the parameter. So we could put logic in TO to try to determine it and switch the output. While that was fairly easy for cachekey there are a lot more things based on that 'filename' parameter for logging. It was fine for testing but actually integrating something like that could get pretty messy. Like to run the logging_dot_config function it triggers off of the logging.config filename, but to use the same params it would still have to trigger off logs_xml, check the ATS version, and then somehow change the filename upstream when it returned

**Comment by alficles** [comment]
lgtm

**Comment by limited** [comment]
Fixes #1126

**Pull request merged**
