### PR TITLE
Anonymous IP TO Implementation

### PR DESCRIPTION
**Pull request by PeterRyder**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/764/
Test PASSed.

**Comment by dneuman64** [comment]
I don't know that I will get to this right away, but I would like to test this out

**Comment by dneuman64** [comment]
Hey @PeterRyder it would be awesome if you could add some docs for this functionality.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/774/
Test PASSed.

**Comment by alficles** [comment]
I see the implementation of the UI, but where are these values consumed? Is there a plugin I'm not aware of that implements this?

**Comment by PeterRyder** [comment]
When the Cr-Config gets generated in the UI::Topology file, the routers will determine if anonymous blocking is enabled or disabled. Then, using some parameters it will get a json config file and the anonymous ip database

**Comment by alficles** [comment]
Aha. I see now. this one depends on #736 .

**Comment by PeterRyder** [comment]
Yes - I figured splitting this into 2 PRs would be easier to review

**Comment by PeterRyder** [comment]
Closing - refer to new PR https://github.com/apache/incubator-trafficcontrol/pull/2226 for 2.3.x rebase

**Pull request closed without merging**
