### PR TITLE
modify storage.config to match PR 497

### PR DESCRIPTION
**Pull request by dg4prez**
Storage.config modified to match the features added in PR 497.  Should be merged when 497 is merged.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-traffic_ops-test-PR/16/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/25/

**Comment by dg4prez** [comment]
Closing pending any change in the status of 497.

**Pull request closed without merging**
