### PR TITLE
Enhanced IPV6 handling in astats 

### PR DESCRIPTION
**Pull request by serDrem**
Enhanced IPV6 handling in astats

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/734/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/812/
Test PASSed.

**Comment by DylanVolz** [comment]
I have tested this PR on a cache and verifies it works.

**Comment by dangogh** [comment]
merging based on reviews from @DylanVolz and @jrushford

**Pull request merged**
