### PR TITLE
WIP - Adding contact information to Tenant's table

### PR DESCRIPTION
**Pull request by wmbrown18**
This is a working progress of adding a contact information from the tenant table. It works, but other a part of the mailing list were deciding on how to make it better. So this is what was made for the time being.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by limited** [comment]
ok to test

**Comment by dangogh** [comment]
Please change the PR title to be descriptive of the change.   WIP is an appropriate label to show it's not complete,  but still must describe the purpose of the change.

Also,  individual commit messages should be descriptive.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1/

**Comment by dangogh** [comment]
Here are some guidelines on contributions that may help:   https://github.com/apache/incubator-trafficcontrol/blob/master/CONTRIBUTING.md#guidelines

**Comment by dangogh** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/5/

**Comment by dangogh** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/11/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/33/

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-traffic_ops-test-PR/10/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/10/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-whatchanged/13/

**Comment by mitchell852** [comment]
closing. let me know if you think otherwise.

**Pull request closed without merging**
