### PR TITLE
Created swaggerdocs for the /asns API

### PR DESCRIPTION
**Pull request by dewrich**
Introduced the /divisions swagger documentation

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1282/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1291/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1303/
Test PASSed.

**Comment by dewrich** [comment]
Fixes https://github.com/apache/incubator-trafficcontrol/issues/1987

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1305/
Test PASSed.

**Pull request merged**
