### PR TITLE
[BACKPORT] [TC-533] - ssl_keys - tenancy checks

### PR DESCRIPTION
**Pull request by mitchell852**
(cherry picked from commit 01452c99a0fc4d459742a67bad3bab9f20fcf4e6)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/56/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-traffic_ops-test-PR/58/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/96/

**Comment by hbeatty** [comment]
@mitchell852 merged - please close

**Comment by hbeatty** [comment]
@mitchell852 merged - please close

**Comment by mitchell852** [comment]
manually closing

**Pull request closed without merging**
